<?php include_once 'view/pattern/header.php' ?>
	<h1>INI. HOME</h1>
	<table>
		<tr>
			<td>--</td>
			<td>NOME</td>
			<td>USUARIO</td>
			<td>SENHA</td>
		</tr>
<?php
	foreach ($view_list as $li) {
		echo "<tr>";
		echo "<td>" . $li->id . "</td>";
		echo "<td>" . $li->nome . "</td>";
		echo "<td>" . $li->usuario . "</td>";
		echo "<td>" . $li->senha . "</td>";
		echo "<td>
				<a href='/System/system/site/home/form/". $li->id ."'>Editar</a>
			  </td>
			  <td>
				<a href='/System/system/site/home/delete/". $li->id ."'>Excluir</a><br>
			  </td>
		";
		echo "</tr>";
	}
	// echo "<pre>";
	// print_r($view_list);
	// echo "</pre>";
	// exit();
?>
	</table>
	<button><a href="/System/system/site/home/form">ADICIONAR NOVO</a></button>
	<!-- <button href="/site/home/form">ADICIONAR NOVO</button> -->
<?php
	include_once 'view/pattern/footer.php'
?>
